name: fablab
description: A new Flutter project.
 
publish_to: 'none'  
 
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0' 
dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.2
  firebase_core: ^1.23.0
  get: ^4.6.5
  firebase_auth: ^3.10.0
  cloud_firestore: ^3.4.9
  ionicons: ^0.2.1
  dropdown_button2: ^1.8.2
  file_picker: ^5.2.0+1
  firebase_storage: ^10.3.9
  very_good_analysis: ^3.1.0
  multi_image_layout: ^0.0.5
  expandable_text: ^2.3.0
  like_button: ^2.0.5 
  comment_tree: ^0.3.0
  anim_search_bar: ^2.0.2
  material_floating_search_bar: ^0.3.7
  badges: ^2.0.3
  flutter_slidable: ^2.0.0
  firebase_database: ^9.1.6
  jiffy: ^5.0.0
  uuid: ^3.0.6
  flutter_native_image: ^0.0.6+1
  flutter_otp_text_field: ^1.1.1
  firebase_messaging: ^13.1.0
  firebase_crashlytics: ^2.9.0
  firebase_performance: ^0.8.3+3
  firebase_in_app_messaging: ^0.6.0+27
  flutter_native_splash: ^2.2.11
  
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0" 
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/app_logo.png"
  min_sdk_android: 21 
flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#FFFFFF"
  #background_image: "assets/logo/app_logo.png"

   
  image: assets/logo/app_logo.png

    
flutter:
 
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
       - asset: assets/fonts/Poppins/Poppins-Light.ttf
       - asset: assets/fonts/Poppins/Poppins-Bold.ttf
       - asset: assets/fonts/Poppins/Poppins-Medium.ttf

         weight: 700
  